# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
  # To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: gloo
    url: https://storage.googleapis.com/solo-public-helm

releases:
  - name: base
    chart: ./base
    wait: true

  - name: gloo
    chart: gloo/gloo
    namespace: gloo-system
    version: 1.3.2
